--> Factorial "Iteration"

In [65]:
number = 5
fact = 1
if number == 1:
    fact = 1
elif number > 0 and number != 1 :
    for i in range(1,number+1):
        fact = fact * i
print(fact)

120


--> Factorial "Recursion"

In [66]:
def factorial(number):
    if number == 1:
        return number
    elif number > 0 and number != 1:
        return number*factorial(number-1)

num = 5
print(factorial(num))

120


--> Fibonacci "Iteration"

In [56]:
num1 = 0
num2 = 1
fib = 10
result = 0
for i in range(0,fib-1):
    result = num1 + num2
    num1 = num2
    num2 = result
print(result)

55


--> Fibonacci "Recursion"

In [1]:
def fib(number):
    if number <= 1 :
        return number 
    else:
        return (fib(number-1)+fib(number-2))

print(fib(10))
    

55


--> Linear Search "Iteration"

In [1]:
import numpy as np
goal = 7
input_arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(len(input_arr)):
    if goal == input_arr[i]:
        position = i
        break
    else :
        position = -1
        
if position == -1:
    print("NOT FOUND")
else :
    print("The Goal is at index = " + str(position))

The Goal is at index = 6


--> Linear Search "Recursion"

In [29]:
def linear_search_rec(arr,i,goal):
    if i < len(arr):
        if arr[i] == goal :
            position = i
            return position
        else :
            position = i+1
            return linear_search_rec(arr,position,goal)
    else :
        position = -1
        return position

input_arr = np.array([1,2,3,4,5,6,7,8,9,10])
goal = 9
start_index = 0

if linear_search_rec(input_arr,start_index,goal) == -1:
    print("NOT FOUND")
else :
    print("The Goal is at index = " + str(linear_search_rec(input_arr,start_index,goal)))
    

The Goal is at index = 8


--> Binary Search "Iteration"

In [43]:
def binary_search(arr,goal):
    low = 0
    high = len(arr)-1
    while low <= high :
        mid = (high + low)//2

        if input_arr[mid] < goal:
            low = mid+1
        elif input_arr[mid] > goal:
            high = mid-1
        elif arr[mid] == goal:
            return mid
        else:
            return -1 #not found
        
input_arr = np.array([1,2,3,4,5,6,7,8,9,10])
goal = 7

if binary_search(input_arr,goal) == None:
    print("NOT FOUND")
else :
    print("The Goal is at index = " + str(binary_search(input_arr,goal)))

The Goal is at index = 6


--> Binary Search "Recursion"

In [44]:
def binary_search_rec(arr,low,high,goal):
    if low <= high :
        mid = (high+low)//2
        if arr[mid]==goal:
            return mid
        elif arr[mid]>goal:
            high = mid-1
            return binary_search_rec(arr,low,high,goal)
        elif arr[mid]<goal:
            low = mid+1
            return binary_search_rec(arr,low,high,goal)
        else:
            return -1 #not found


input_arr = np.array([1,2,3,4,5,6,7,8,9,10])
goal = 4
low = 0
high = len(input_arr)-1

if binary_search_rec(input_arr,low,high,goal) == None:
    print("NOT FOUND")
else :
    print("The Goal is at index = " + str(binary_search_rec(input_arr,low,high,goal)))

The Goal is at index = 3


--> Insertion Sort "Iteration"

In [47]:
def insertion_sort(arr):
    for i in range(1,len(arr)): #1 to skip the 1st element which is already in the sorted list
        value_to_sort = arr[i]
        while i > 0 and arr[i-1] > value_to_sort:
            arr[i] , arr[i-1] = arr[i-1],arr[i]
            i = i-1     
    return arr

input_arr = np.array([4, 22, 41, 40, 27, 30, 36,-2,100])
print(insertion_sort(input_arr))


[ -2   4  22  27  30  36  40  41 100]


--> Insertion Sort "Recursive"

In [52]:
def insertion_sort_rec(arr,i):
    value_to_sort = arr[i]
    while i > 0 and  arr[i-1] > value_to_sort:
        arr[i],arr[i-1] = arr[i-1],arr[i]
        i = i-1
    if (i+1 < len(arr)):
        insertion_sort_rec(arr,i+1)   
    return arr

input_arr = np.array([4, 22, 41, 40, 27, 30, 36,-2,100])
print(insertion_sort_rec(input_arr,1))

[ -2   4  22  27  30  36  40  41 100]


--> Selection Sort 

In [53]:
arr = np.array([4, 22, 41, 40, 27, 30, 36,-2,100])

for i in range(len(arr)):
    min = i
    for j in range(i+1 , len(arr)):
        if arr[min] > arr[j]:
            min = j
    arr[i],arr[min] = arr[min],arr[i]
            
print(arr)

[ -2   4  22  27  30  36  40  41 100]


--> Bubble Sort

In [54]:
def bubble_sort(arr):
    sorted = False
    while not sorted:
        sorted = True
        for i in range(0,len(arr)-1):
            if arr[i] > arr[i+1]:
                sorted = False
                arr[i],arr[i+1] = arr[i+1],arr[i]
    return arr

arr = np.array([4, 22, 41, 40, 27, 30, 36,-2,100])
print(bubble_sort(arr))    

[ -2   4  22  27  30  36  40  41 100]


--> Bubble Sort "With Swap"

In [55]:
def bubble_sort_swap(arr):
    sorted = False
    while not sorted:
        sorted = True
        swapped = False
        for i in range(0,len(arr)-1):
            if arr[i] > arr[i+1]:
                sorted = False
                arr[i],arr[i+1] = arr[i+1],arr[i]
                swapped = True
        if swapped == False:
            break
    return arr

arr = np.array([4, 22, 41, 40, 27, 30, 36,-2,100])
print(bubble_sort_swap(arr)) 

[ -2   4  22  27  30  36  40  41 100]


--> GCD

In [56]:
def gcd(x, y):
    for i in range(1, x+1):
        if((x % i == 0) and (y % i == 0)):
            gcd = i
              
    return gcd

print(gcd(48,60))

12


--> GCD "With Euclidean Lemma"